### ISSUE TITLE
D5.16: PARI suite release ( libpari , GP and GP2C ) that fully support parallelisation allowing individual implementations to scale gracefully between single core / multicore / massively parallel machines.

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#114] opened 2015-09-08 20:17 UTC
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** CNRS
- **Due:** 2019-08-31 (month 48)
- **Nature:** Demonstrator
- **Task:** T5.1 (#99) 
- **Proposal:** [p. 51](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.16/report-final.pdf)** ([sources](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP5/D5.16/))

**The Pari library** is a state-of-the-art library for number theory and an important component of the Sage computational system. Together with the `gp` command line interface and the `gp2c` compiler, it forms the Pari/GP package. This deliverable implements a generic parallel engine in the Pari/GP system, uses it inside the system to implement fast parallel variants of existing sequential code and exports it for library users. The released Pari/GP suite (PARI-2.12) makes those improvements and new features available for the community, in particular Sage users and all softwares using the Pari library.

The MultiThread engine transparently supports: 1) sequential computation, 2) POSIX threads (for a single multicore machine) and 3) Message Passing Interface (MPI, for clusters). It is used throughout the library to improve a large number of high-level mathematical algorithms, including fast linear algebra over the rationals or cyclotomic fields, fast Chinese remainders, resultants, primality proofs, discrete logarithms, modular polymomials and isogeny-based algorithms, motivic L-functions... Those implementations scale transparently between single core, multicore and massively parallel machines.

**Comment by bpilorget** [comment] 2018-01-11 13:27
#108 was merged into #114 after 3rd amendment to the contract

**Comment by IzabelaFaguet** [comment] 2019-04-16 09:25
Hello everyone!
We are organising an ODK report writing sprint From August 24th to August 31st,
a good opportunity to finish the final reports in a pleasant and friendly environment.
Would someone like to participate?

**Comment by KBelabas** [comment] 2019-08-22 13:48
D5.16 is ready for comments / proofreading at OpenDreamKit/WP5/D5.16

**Comment by JohnCremona** [comment] 2019-08-22 15:04
On Thu, 22 Aug 2019 at 14:48, Karim Belabas <notifications@github.com>
wrote:

> D5.16 is ready for comments / proofreading at OpenDreamKit/WP5/D5.16
>

I read it and it looks good.   Although the reviewers may not appreciate
it, it is impressive that the examples you give are of a very high
mathematical level so this is not just impressive software engineering but
is likely to make quite an impact among computational mathematicians.

(And thanks for updating the bound on the elliptic curve database!)

John

**Comment by nthiery** [comment] 2019-08-23 09:53
Salut Karim, Bill,
Thanks a lot! I really appreciate the report delivery well ahead of time:-)
I have (proof)read the report (except the documentation in the appendix), and it looks very good to me (playing the non expert guinea pig). 

Only three minor requests / suggestions:
- [ ] Edit the first comment in this issue to add an abstract for the report. See e.g. #143 for an example. It will then be included in the pdf when I'll generate it.
- [ ] Please rename the latex source to `report.tex` for consistency
- [ ] About section 3: could you use plots to present the timing results? Typically for the first sentence of p.7? In similar circumstances, our reviewers requested this; they like visual material :-)

**Comment by nthiery** [comment] 2019-08-23 09:56
@ClementPernet: please review!

**Comment by KBelabas** [comment] 2019-08-24 11:16
New version available adressing Nicolas's comments.

**Comment by nthiery** [comment] 2019-08-24 15:15
Thank you Karim!
Per your request, I updated the github issue description from the git repo. I made a small edit as well (removing the two first slightly redundant paragraphs). Of course I screwed up a bit, so the git history is not as clean as it should be :-)
I also pushed the pdf so that people can get it by following the "report" link above.

**Comment by KBelabas** [comment] 2019-08-24 17:40
Looks good, thanks !

**Comment by nthiery** [comment] 2019-08-26 15:05
Suggestion: please prepare a demo in notebook format; see #289.

**Comment by jdemeyer** [comment] 2019-08-26 16:46
I updated the report with typos and minor rewordings. I also removed the very last part showing the equivalent GP code of the cypari2 code, since I didn't see the point of that (the section is about external applications).

**Comment by KBelabas** [comment] 2019-08-27 16:01
Proofread again, no problem with your modifications. Thanks !

**Comment by nthiery** [comment] 2019-08-27 17:13
Great to see this very close to done! @ClementPernet : do you have a chance to review it shortly? Then I can submit it and remove it from my plate :-) Thanks!

**Comment by ClementPernet** [comment] 2019-08-28 13:41
@nthiery : I have reviewed it and already asked for some edits. @KBelabas already did some, told me he would add one more graph with speedups as I had asked. As soon as it is done, I the report will be ok to be sent.

**Comment by nthiery** [comment] 2019-08-28 15:06
> @nthiery : I have reviewed it and already asked for some edits. @KBelabas already did some, told me he would add one more graph with speedups as I had asked. As soon as it is done, I the report will be ok to be sent.

Excellent. Thanks!

**Comment by ClementPernet** [comment] 2019-08-29 11:08
Thanks @KBelabas for the new figure. One last remark: it would be very informative to have not only the speedups but also the timing value: for instance, simply add in the text what is the time of the sequential computation.

**Comment by KBelabas** [comment] 2019-08-29 14:51
Thanks for the review. Done!

A minor change of strategy in matker() gave an extra x 2 speedup almost for free, without any regression this time (compared to previous attempts). This allowed to move rational reconstruction to parallel section,  while keeping most of the early aborts. So I changed that data as well: the final figure looks better now :-)

**Comment by nthiery** [comment] 2019-08-29 14:57
Yeah! x2 almost for free is always good to take :-)

Should I proceed with the submission?

**Comment by ClementPernet** [comment] 2019-08-29 15:13
Excellent! I've nothing left to bug @KBelabas . I guess the report is good to go now!

**Comment by nthiery** [comment] 2019-08-29 15:45
Congrats on being the first submitted deliverable of this reporting period :-)

Thanks everyone for all the work and reporting!

**Comment by ClementPernet** [comment] 2019-08-30 11:45
@KBelabas @videlec : could you also update the progress report on Task T5.1 (which is essentially this deliverable) in section 1.2.5.2 of https://github.com/OpenDreamKit/OpenDreamKit/blob/master/ReportingPeriod3/TechnicalReport/WP5.tex
You can also just send me a paragraph and I'll edit the file.
Thanks

**Comment by KBelabas** [comment] 2019-08-30 15:49
Summary inserted in WP5.tex, replacing previous template.

**Comment by ClementPernet** [comment] 2019-10-18 12:10
@KBelabas @videlec (can you forward to Bill as well) : 
I am preparing the presentation of WP5. There are 4 deliverables due for M48 and this is one of them. Since it is the only deliverable about PARI (D5.10 being merged into this one) I think it will be important to highlight the achievements of this deliverable. Can you prepare a few slides (about 4-5) summarizing the main achievements  in this deliverable, and the perspectives and new directions which follow from this work.
My slides for WP5 will be beamer slides, so you can
- prepare beamer slides
- or just list the content in plain text, and I can beamerize them.
I will need to have this ready before sunday 27.
Thanks.

**Comment by KBelabas** [comment] 2019-10-27 13:13
* Clément Pernet [2019-10-18 14:28]:
> @KBelabas @videlec (can you forward to Bill as well) : 
[...]
> My slides for WP5 will be beamer slides, so you can
> - prepare beamer slides
> - or just list the content in plain text, and I can beamerize them.
> I will need to have this ready before sunday 27.
> Thanks.

Hi Clément,

  Here is a first draft. Does it cover what you expected ? I have drawn
mostly from the report.

Bill, Vincent : feel free to comment or change anything you don't like :-)

Cheers

    K.B.

P.S. Clément: there's an Atelier PARI/GP in Grenoble in january (20 to 24th)
http://pari.math.u-bordeaux.fr/Events/PARI2020/
I hope we can register you ? :-)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Text within [ ... ] is not so important and can left for oral comments,
or left out altogether.

SLIDE 1: Main achievements (MT Engine)

We released a Multi-Thread engine for the complete PARI suite (Pari library,
GP shell, GP2C compiler). It supports
  * Sequential computation,
  * POSIX threads,
  * Message Passing Interface (MPI),
within the same code base. The MT Engine is easy to setup
(Configure --mt=pthread, that's it). Part of it is transparent to users
(automatic implicit parallelism), part of it mirrors standard control
structures (for / parfor). [ Power users and developpers have complete
control on low-level aspects if they so desire. ]

SLIDE 2: Main achievements (libpari development)

  * Fast linear algebra over the rationals and cyclotomic fields
  * Fast Chinese remainders and multimodular reduction
  * Parallel polynomial resultant [not yet quasi-linear]
  * Fast modular polynomials and applications: ECPP primality proving, SEA
    and Satoh point-counting
  * MPQS integer factorization rewrite

Well-honed strategy after preliminary assessment:
  * Improvement of code quality: refactoring, interface clarification
  * Creation of "worker" functions from existing code
  * Insertion of actual parallel instructions
[ Incremental buildup, independently instrumenting one high-level function at
a time. ]

SLIDE 3: Highlight (Fast linear algebra)

Linear algebra over the rationals was a major bottleneck for independently
developped packages: 
  * Modular Symbols (2013-18)
  * Modular Forms (2016-19).

These packages provided the main motivation and diverse testing grounds for
fast linear algebra using modular techniques, including but not limited to
parallelization:

  * linear algebra over cyclotomic rings (Bill Allombert, 2016-17)
  * fast multi-modular reduction and Chinese remainders (Bill Allombert, 2017)
  * fast CUP decomposition over finite fields (Peter Bruin, 2018)
  * parallelize through MT engine (Bill Allombert, Karim Belabas, 2017-19)

SLIDE 4: Highlight (Example of speedups)

Using POSIX threads on a server with 8 physical cores (32 logical cores
through HyperThreading)

  <picture, see attached image.tgz>

[ Compared to ellan, linear algebra involves more overhead: 3 atomic
parallelized operations (reducing inputs, modular linear algebra, Chinese
remaindering). In addition, matker wastes time in the main thread to check
the result. ]

SLIDE 5: Perspectives and new directions

In the continuity of ODK work:
  * Parallelize MPQS integer factorization
    [scheduled for end of year]
  * Parallelize numerical summation and integration routines
    [scheduled for 2020: not done yet because no impact outside of the
    routine itself]
  * Parallelize black-box linear algebra (block Lanczos or Wiedemann)
    [scheduled for 2020: sequential code to be written first]

Outside of ODK scope: major projects that will both benefit from the newly
developped parallel code \emph{and} will themselves need to be parallelized
  * Elliptic curve descent and prerequisite algebraic number theory (class
    groups and units, compact units, principal ideal generators)
  * Linear algebra over Z (HNF for class group computation)
[ Existing PARI or GP code already provides this, but in obscure or
inefficient ways. Major cleanup / overhaul needed. Can be done in an
incremental way, function by function. ]

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
--
Karim Belabas, IMB (UMR 5251)  Tel: (+33) (0)5 40 00 26 17
Universite de Bordeaux         Fax: (+33) (0)5 40 00 21 23
351, cours de la Liberation    http://www.math.u-bordeaux.fr/~kbelabas/
F-33405 Talence (France)       http://pari.math.u-bordeaux.fr/  [PARI/GP]
`

**Closed** 2019-12-16 22:24 UTC
Labels: FormatCheck, PARI-GP, ReportingPeriod3, UB, WP5, deliverable, delivered
