### ISSUE TITLE
Prepare the Formal Review presentations

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#222] opened 2017-03-02 09:47 UTC
This issue is to prepare the  presentations for the formal review.

- [Agenda, with links to the slides on the review website page](http://opendreamkit.org/2017/04/24/first-project-review/)
- Notes on the content in the [README](https://github.com/OpenDreamKit/OpenDreamKit/blob/master/README.md#organization-of-official-meetings)
- Notes on the content in the [Edinburgh steering committee minutes](http://opendreamkit.org/meetings/2017-01-19-EdinburghSteeringCommittee/steering-minutes/)
- [Source files for the slides](https://github.com/OpenDreamKit/OpenDreamKit.github.io/tree/master/meetings/2017-04-26-ProjectReviewPresentations). 

# Demonstrations

- [ ] Math-In-The-Middle demonstration? (@kohlhase, @alex-konovalov, ...)
- [ ] Jupyter-OOMMF: Using the notebook to drive a micromagnetic simulation  (Hans)
- [ ] ???

# Posters

- [ ] Jupyter-OOMMF (Hans)
- [ ] ???

# References on the review content

# From the official letter from EU:

``The review will cover the project activities that you have carried out
during the first reporting period.  It will examine:

- the degree to which the work plan has been carried out and whether all deliverables were completed
- whether the objectives are still relevant and provide scientific or industrial breakthrough potential
- how resources were planned and used in relation to the achieved progress, and if their use respects the principles of economy, efficiency and effectiveness
- the management procedures and methods of the project
- the beneficiaries’ contributions and their integration within the project
- the expected potential scientific, technological, economic, competitive and social impact, and plans for using and disseminating results
- eligibility of the costs claimed
- compliance with other grant agreement obligations.

It will also cover the work of third parties involved in the project (e.g. linked third parties, third parties giving in-kind contributions, subcontractors, etc).''

Additional tip from our PO: ``Please make sure that all presentations are to the point and do not unnecessarily repeat the information given in the deliverables and reporting. Make sur there is sufficiently time for Q&A in each session.''

REMINDER: HAVE TO BE PRESENT: All WP leaders + Coordinator + project manager AND at least one representative per site

## Faciliies

Monday Morning: small (10 people) meeting room with beamer
Monday Afternoon: medium (20 people) meeting room + small (10 people) meeting room Closing of rooms: 8:30 pm

Tuesday: All day medium (20 people) meeting room + small (10 people) meeting room Closing of rooms: 8:30 pm

Wednesday: All day big (40 sitting people, max 60) meeting room

NB: from the looks of photos, the maximum amount of persons per room is most probably underestimated

**Comment by fangohr** [comment] 2017-03-09 07:13
Let's start with the constraints: we have a whole day (from when to when?) and how many rooms (@bpilorget?) at the same time to show what we have done.

**Comment by fangohr** [comment] 2017-03-09 07:16
I really liked the suggestion of having posters or (probably better:) demonstrators where reviewers can quiz some of us in greater detail - this allows them to follow their interests. I also think - at least for the parts of the project I know - that a life demonstration (or ability of the reviewer to run a demonstrations themselves) can show important aspects of the work that we cannot communicate well in talks. 

It would actually also be interesting for us to see code in action that has been developed in various places.

**Comment by fangohr** [comment] 2017-03-09 07:23
Here is a first draft an agenda, based on the idea that we have some talks and some demonstrations. I think brief talks first, then the demonstrator session is best.

9:00 arrival and coffee
9:30 Welcome and overview of the day, maybe quick overview of project (Nicolas)
Various talks [needs to be discussed]
11:00 Coffee break
11:30 demonstrator and poster session
13:00 lunch 
14:15 Reviewers private meeting (if that is the normal thing)
15:00 Coffee
15:30 Feedback and discussion with reviewers
16:00 Closing comments

We could push the demonstrators into the afternoon, giving more time for talks in the morning. 

Or do something completely different. Might also be worth asking the project officer for advice?

@wdecker - what do you recommend, based on your experience?

**Comment by bpilorget** [comment] 2017-03-09 09:04
Hans for the rooms see #223

**Comment by bpilorget** [comment] 2017-03-09 16:02
Dear Hans, thank you for drafting this agenda. I think presentations deserve more time, especially since 1 presentation per WP will be needed. Maybe we can plan to end the meeting at 5:30 pm / 6pm?

**Comment by fangohr** [comment] 2017-03-09 16:42
Sure, just wanted to get the discussion going ;) 

We could also have one or a few talks that are 'orthogonal' to the work packages and present one or two or three activities that extends over multiple work packages. The talk I gave in Edinburgh about the micro magnetic demonstrator is a possible candidate for this: it explains some of the motivation for the project (i.e. what is not ideal at the moment), then touches on Component Architecture, User Interfaces and Dissemination WorkPackages. This may make it easier to tell a story to the reviewers, rather than presenting one aspect (i.e. one WorkPackage) in great details, without much context.

**Comment by JohnCremona** [comment] 2017-03-09 16:56
Surely the great EU machine has specified how long the session should be,
start time and latest finish time?  I cannot imagine that any EU official
works overtime.

**Comment by dimpase** [comment] 2017-03-09 17:08
surely, 40+ years of shameless local anti-EU propaganda must have left a mark on John...

**Comment by dimpase** [comment] 2017-03-09 17:27
In case anyone wonders, working days in sessions of the EU Parliament last for about 14 hours.
See e.g. [here](http://www.europarl.europa.eu/sides/getDoc.do?type=AGENDA&reference=20170314&secondRef=SIT&language=EN).

**Comment by JohnCremona** [comment] 2017-03-09 17:31
On 9 March 2017 at 17:27, Dima Pasechnik <notifications@github.com> wrote:

> In case anyone wonders, working days in sessions of the EU Parliament last
> for about 14 hours.
> See e.g. here
> <http://www.europarl.europa.eu/sides/getDoc.do?type=AGENDA&reference=20170314&secondRef=SIT&language=EN>
> .
>

I thought someone would interpret my comment as anti-EU, but it was not
meant that way!  (But do MEPs get paid by the hour I wonder...)

**Comment by dimpase** [comment] 2017-03-09 17:41
@JohnCremona MEPs are paid [38.5% of the basic salary of a judge](http://www.richardcorbett.org.uk/transparency/salary-expenses/) in  the European Court of Justice. About 6200 euro p.m. after tax.

**Comment by nthiery** [comment] 2017-03-09 22:27
Thanks @fangohr for getting the ball rolling. I am about to copy your initial draft of schedule to the first comment and will do some edits.

Cross-work package presentation(s) would be nice indeed. In fact, I already asked @mikecroucher if he could prepare a short (20min?)  version of his talk [Is your research software correct?](https://mikecroucher.github.io/MLPM_talk/). I believe it sets up the stage very nicely, highlighting the challenges faced by researchers and the type of solutions needed. And then many of our actions come naturally as leveraging these solutions. E.g:

- Automate (aka learn to program): our focus on REPL/programming
  interaction with the software rather than clic-clic-clic
- Write code in a (very) high-level language: ?
- Get some training: all our dissemination actions
- Use version control: nbdime, ...
- Get a code buddy (Maybe an RSE!): ?
- Share your code and data openly: that's at the core of our approach
  and we foster it further in our communities
- Use literate computing technologies: notebooks!
- Write tests: nbval, ...

I like your talk too for highlighting the range of applicability of our work outside of the pure math world.

At the same time, we will also need some more down to earth WP by WP presentations; the trick will be to strike the right balance.

**Comment by bpilorget** [comment] 2017-03-10 13:51
@JohnCremona Actually the agenda is up to the project. It can be organised and last as long as we want

**Comment by nthiery** [comment] 2017-03-21 13:25
Hi,
I have reworked a tiny bit the tentative agenda for the review meeting (adding 1/2 hour for the WP presentations). With that, we have 1.5 hours for "2-3 story telling presentations" and three hours for the WP presentations. This means:

- about 25 minutes per story telling presentation
- 30 minutes per WP presentation, including questions and transitions (WP1 and WP2 should be quite short; so I counted them as a single WP).
- two hours (including coffee breaks) for posters and live demonstrations

WP leaders: does this sound right? The idea is to give the big picture for each WP, with an overview of the aims and progress, mentionning briefly deliverables, but not diving into their details.

Everyone: does this sound right?

I am wondering whether we would want to allocate a specific time for a Q&A session, where we would let the reviewers lead the discussion with questions, and dig in points of interests to them (e.g. about a specific deliverable, or partner, or ...).

**Comment by bpilorget** [comment] 2017-03-21 16:55
Considering I will need to present the use of resources-/KPIs, , and that many many dissemination events are organised that could last a bit more than 30 min for both of them.

**Comment by fangohr** [comment] 2017-03-21 18:49
Hi Nicolas, 

the agenda looks very reasonable to me. 

Just two comments/questions; none of them major:

1. I would possibly skip the demonstrations at 9:00, and instead get project partners to set up posters / demonstrations in that time, and use the 30 minutes for a leisurely arrival of reviewers, informal introductions etc. As we haven't been in the particular room yet (if I recall correctly), we may need some time to sort ourselves out with the prensetations. Alternatively, we need to have project partners there by 8:30 or 8:45 the latest for a start at 9:00. That's also an option, but it seems a little bit odd to have the presentations before we had any introduction, and also spreading the presentations over 3 slots might be quite fractured? I think the 11:00 to 12:00 presentation slot is great and should be seen as the main activity, with an option to come back to one or two in the later coffee break.

2. The wrap up at 16:00 is presumably to catch up if we have overrun, or to address any immediate concerns, but really could be a very brief thank you statement? Or can we (you?) say something that pulls together the presentations from the work packages to make the whole project look coherent (again, after the WP will have focussed on details in quite different topic areas). That might be quite useful.

In response to the length of time for each WP: @bpilorget, not sure what exactly you have to present but if there is a long list of events that takes 15 minutes to explain, maybe we should short cut this (mentioning a few of them in detail, then display a list?).

I am sure more thoughts will emerge over time.

Any other ideas/suggestions/concerns?

**Comment by fangohr** [comment] 2017-03-21 22:21
Forgot to respond to the idea of the Q&A session: I wouldn't schedule anything on this. This is the kind of questioning that the reviewers can either conduct informally during the poster sessions, or at the end of each talk (where I expect we invite questions - in fact I would suggest to encourage questions throughout all presentations, while at the same time we will not overrun ...). 

Finally, the feedback and discussion with reviewers is another opportunity for this kind of exchange. So my personal preference would be for ongoing exchange of ideas/concerns/questions, and not to schedule an extra time slot for this.

**Comment by nthiery** [comment] 2017-03-22 09:13
On Tue, Mar 21, 2017 at 09:55:58AM -0700, bpilorget wrote:
>    Considering I will need to present the use of resources-/KPIs, , and
>    that many many dissemination events are organised that could last a bit
>    more than 30 min for both of them.

The reviewers will already have read a detailed reports about the
events for year 1 (D2.2). Briefly stating some figures about all the
events organized (number, types, total number of participants, ...),
with highlights on a few typical ones (maybe Women in Sage, Cernay,
and the Jupyter one in Edinburgh?) should be enough, shouldn't it?
That part would then take no more than five minutes.

Cheers,
                                Nicolas

**Comment by VivianePons** [comment] 2017-03-22 09:30
Yes, I agree, I think it should take me 10~15 minutes to present to whole
WP.

2017-03-22 10:13 GMT+01:00 Nicolas M. Thiéry <notifications@github.com>:

**Comment by nthiery** [comment] 2017-03-22 10:12
>    Forgot to respond to the idea of the Q&A session: I wouldn't schedule
>    anything on this. This is the kind of questioning that the reviewers
>    can either conduct informally during the poster sessions, or at the end
>    of each talk (where I expect we invite questions - in fact I would
>    suggest to encourage questions throughout all presentations, while at
>    the same time we will not overrun ...).
> 
>    Finally, the feedback and discussion with reviewers is another
>    opportunity for this kind of exchange. So my personal preference would
>    be for ongoing exchange of ideas/concerns/questions, and not to
>    schedule an extra time slot for this.

Ok, sounds good; no specific Q&A session then, unless someone really
cares for it. Thanks Hans for the feedback.

**Comment by nthiery** [comment] 2017-03-22 11:26
We need a good concise title for the 9:45 session, which is about short cross work-package presentations telling a story to set up the stage. Here are some I came up with, but am not happy about:
- Cross work-package presentations
- User stories
- Overview presentations

**Comment by nthiery** [comment] 2017-03-22 11:27
Also: in this session, we would need a mathematics-centered story.

**Comment by nthiery** [comment] 2017-03-22 15:35
Feedback from our PO:
- Start at 9 am sharp with a welcome (remove the 20 mins arrival)
- Move the session 1 at the end – I’d prefer to have all the all technical work presented as a priority
- Closed reviewers + PO meeting at 16-17:00 parallel with the coffee break
- Feedback and discussion at 17:00

**Comment by nthiery** [comment] 2017-03-22 16:15
With @bpilorget, we refactored the agenda according to our PO suggestions. Please check. Now the poster and demonstrations will be during the morning coffee break and lunch break.

**Comment by fangohr** [comment] 2017-03-22 17:45
Would it make sense to Mike Croucher's talk first, and then the Jupyter show case? Mike's talk basically outlines all the things that can go wrong, and in in the Jupyter-OOMMF story we start to address that with solutions, so it would be natural to outline the problems first? (@mikecroucher)

**Comment by nthiery** [comment] 2017-03-22 23:06
>    Would it make sense to Mike Croucher's talk first, and then the Jupyter
>    show case?

Good point! I changed that.

**Comment by bpilorget** [comment] 2017-03-24 09:31
@nthiery The agenda is good to go?

**Comment by nthiery** [comment] 2017-03-24 10:18
I would not mind having a good title for the "cross workpackage presentation session". And a third presentation title. Other than that, it's good to go. So go ahead if need me.

**Comment by fangohr** [comment] 2017-03-24 10:43
Words like 'context' and 'motivation' would be good to refer to Mike's talk as he outlines what the challenges are. It's not so clear how we capture the first results we include, that these go across work packages but are also not at all an exhaustive representation of the project (other than through 'case study'). Maybe 'Context and case study'? I think we can improve on this, input is welcome, but we also need to move on with this.

**Comment by nthiery** [comment] 2017-03-24 10:56
>    Words like 'context' and 'motivation' would be good to refer to Mike's
>    talk as he outlines what the challenges are. It's not so clear how we
>    capture the first results we include, that these go across work
>    packages but are also not at all an exhaustive representation of the
>    project (other than through 'case study'). Maybe 'Context and case
>    study'? I think we can improve on this, input is welcome, but we also
>    need to move on with this.

I like "Some context and case study". Let's go with that. Thanks Hans!

**Comment by nthiery** [comment] 2017-03-24 13:14
About a third more mathematically oriented "Context and case study": what about a quick demo of using SageMathCloud + Jupyter for collaborative experimental research and teaching?
@VivianePons: would you be up for it?

**Comment by bpilorget** [comment] 2017-03-24 13:48
That would be a good idea! It definitely gives a better picture of how the ODK VRE can be used on a daily basis! 👍

**Comment by VivianePons** [comment] 2017-03-24 14:47
Sure, that sounds feasible.

2017-03-24 14:48 GMT+01:00 bpilorget <notifications@github.com>:

**Comment by bpilorget** [comment] 2017-03-29 15:09
Agenda is set: no more changes allowed

**Comment by bpilorget** [comment] 2017-04-18 10:28
http://opendreamkit.org/2017/04/24/first-project-review/

**Comment by nthiery** [comment] 2017-04-18 14:12
The slides for the presentations have to be ready for the rehearsals next Monday. Better is if they are ready before than this so that we can start cross-reading them.

We had a strong recommendation from @wdecker to present demos and posters, and we all agreed it was a good idea. Now who is preparing/bringing one?

@minrk has implemented a new feature allowing to let a Jupyter notebook play its content automatically; this can be a good way to prepare a demo.
See #228 and https://github.com/minrk/nbautoplay for the end result and an example.

**Comment by kohlhase** [comment] 2017-04-18 16:56
> Files for presentations at the review are located in this folder: https://github.com/OpenDreamKit/OpenDreamKit.github.io/tree/master/meetings/2017-04-26-ProjectReviewPresentations

Do you really mean that we should use the files for the presentations rather than our own PDFs?

**Comment by bpilorget** [comment] 2017-04-18 17:45
Yes, as much as possible. Templates of the presentations should be the same to show that we work as a consortium. But maybe you prefer a PDF tempalte? I don't minde doing one.

**Comment by kohlhase** [comment] 2017-04-18 17:49
I personally do my slides in LaTeX with ```beamer.cls```, and I thought many of the others do so as well. But I will do whatever is necessary.

**Comment by kohlhase** [comment] 2017-04-18 17:55
How do other's feel?

**Comment by kohlhase** [comment] 2017-04-18 17:56
I am looking at the generated slides, and the generated parts are nice, but there are still problems. 
In the WP6 slides I find: (see the mathcal and ensuremath). 
D6.2: Initial ensuremath mathcal DKS base Design (including base survey and Requirements Workshop Report)

**Comment by kohlhase** [comment] 2017-04-18 17:59
Also I am not sure that starting with the deliverables is a good idea. I would like to give a reminder for WP6 in general and talk about the workshops we had and the MitM architecture that evolved from that. And then I would come to the deliverables. 
You have the "big achievements" after the deliverables.

**Comment by bpilorget** [comment] 2017-04-18 18:02
The content is up to you. What is given here is the template of the document (with images and project's logo). You can fill in the presentations as you like and we'll see next week how smoothly everything goes.

**Comment by nthiery** [comment] 2017-04-18 18:09
>    I am looking at the generated slides, and the generated parts are nice,
>    but there are still problems.
>    In the WP6 slides I find: (see the mathcal and ensuremath).
>    D6.2: Initial ensuremath mathcal DKS base Design (including base survey
>    and Requirements Workshop Report)

Ah, good to know. This must come from the translation of the pdata
from latex to yaml, where we do some stripping of latex markup, but
apparently not enough. I'll have a look.

**Comment by mikecroucher** [comment] 2017-04-18 18:10
The schedule says that I am to give a shortened version of my 'Is your Research Software Correct?' talk as an opener.  I'm hoping that I can use the slide deck I always use -- 

https://mikecroucher.github.io/MLPM_talk/ 

Will this be OK? Converting to pdf tends not to work well for this slide deck

**Comment by bpilorget** [comment] 2017-04-18 18:16
I don't exactly remember how it looks. Is it possible for you to include a first slide before everything else just for the review? With the title and the ODK logo.

**Comment by wbhart** [comment] 2017-04-18 18:19
On 18 April 2017 at 16:12, Nicolas M. Thiéry <notifications@github.com>
wrote:

> The slides for the presentations have to be ready for the rehearsals next
> Monday. Better is if they are ready before than this so that we can start
> cross-reading them.
>

I will be working on slides for KL between now and Friday, (though I am
actually supposed to be on leave until then).

I am a little bit concerned about the requirement to not repeat what is in
the final reports. Had I known that, I wouldn't have put absolutely
everything in the final report! There's literally nothing else to say.

Also, who are we presenting this to? What background will they have? Are
the different WP's being handled differently?

BTW, apparently I am coming to the meeting itself, some time on Monday.

Who is giving the talks? Is Clement, for example, giving the entire
presentation for all the HPC related tasks, or will we be presenting our
own slides?

> We had a strong recommendation from @wdecker <https://github.com/wdecker>
> to present demos and posters, and we all agreed it was a good idea. Now who
> is preparing/bringing one?
>
We have not prepared a Singular poster as of yet, and it isn't clear what
we could demonstrate on the computer that would be visually worthwhile. The
performance stuff isn't really ideally suited to demos.

Someone asked about Singular workshops. Off the top of my head, I don't
recall any, but I passed the question on to Wolfram who has a better memory
than me.

Bill.

P.S: the @wdecker, @wbhart thing doesn't work as expected. I get *all*
OpenDreamKit emails and so there is no distinction between ones which
references me directly and everything else. I try to keep up, but there are
just too many.

**Comment by bpilorget** [comment] 2017-04-18 18:32
Hi,
All this will be presented to the Project Officer (she is not expert enough on our field so she is more here for administrative and financial matters) and to three experts: Peter Dzweg (Concertant LLP, Summa Ventures Ltd) and Wil Schilders (Platform Wiskunde Nederland, TU Eindhoven who were oth present last time, and to Maria Perez from the Universidad Politecnica de Madrid.

Concerning the requirement not to repeat what was written in the deliverables, it means that not absolutely everything must be repeated. If there's nothing more to say compared to the deliverables, it simply needs to be shortly presented of the WP, give an overview of the carried out work and experts will ask questions if they have any (and they will!).

WPs are all treated the same.

In theory WPs are presented by the work package leaders. But if you feel better with another organisation please feel free to reallocate speaking times within yourselves.

@VivianePons Bill Hart began to answer your question about the conferences

@wbhart Don't worry if you feel lost. In this epriod there is a lot of notifications. If you are lsot don't hesitate to contact me or Nicolas for help and/or information

**Comment by nthiery** [comment] 2017-04-18 18:33
>    How do other's feel?

I'd say that it's good to use the same format, but not absolutely
necessary. If someone has a strong preference (e.g. because of
specific needs or existing material) that's fine as long as there is
some consistency in the layout (mostly the first page).

At the end of the review, we can have a brief debriefing and see if we
want to impose one format or the other for the next round.

**Comment by nthiery** [comment] 2017-04-18 18:36
>    I don't exactly remember how it looks. Is it possible for you to
>    include a first slide before everything else just for the review? With
>    the title and the ODK logo.

+1; don't waste time converting your nice set of slides.

**Comment by nthiery** [comment] 2017-04-18 18:47
>    I will be working on slides for KL

Just to confirm on Benoit: there is no need for site-specific slides
for the review; just coordinate with your WP leader for how to present
the WP material if needed.

As for the steering committee meeting: given that we already had a
meeting three months ago, we won't bother making site slides.

**Comment by wbhart** [comment] 2017-04-18 18:49
On 18 April 2017 at 20:32, bpilorget <notifications@github.com> wrote:
>
> In theory WPs are presented by the work package leaders. But if you feel
> better with another organisation please feel free to reallocate speaking
> times within yourselves.
>
I have no problem with WP leaders presenting the slides. Clement has asked
me to provide him with slides, and I will do so.

One further question: what is the reason for the presentations? In other
words, what are we trying to achieve that isn't achieved via the final
reports (other than tick off an EU requirement)? Is the main thing to give
referees a chance to ask questions of us? Or are we also trying to inform
ourselves? Or is there some other stated objective?

Bill.

**Comment by wbhart** [comment] 2017-04-18 18:52
Sorry, I wasn't clear. I will be working on the slides for the WP that KL
has contributed to. This is to save Clement making all the slides for the
entire WP.

I assume these slides will discuss the deliverables we were responsible
for. Clement has asked for 2-3 slides per deliverable. I assume that's
reasonable. I think we also agreed to provide an update on one of the
deliverables which isn't due yet.

**Comment by nthiery** [comment] 2017-04-18 18:56
>    I have no problem with WP leaders presenting the slides. Clement
>    has asked me to provide him with slides, and I will do so.

Oh, I see. You have in mind slides about KL achievements within WP5,
not slides about KL in general (though the difference is of course
slim given that KL is mostly involved in WP5).

>    One further question: what is the reason for the presentations?
>    In other words, what are we trying to achieve that isn't achieved
>    via the final reports (other than tick off an EU requirement)? Is
>    the main thing to give referees a chance to ask questions of us?
>    Or are we also trying to inform ourselves? Or is there some other
>    stated objective?

The aim is to help them grasp the big picture. Which can be easier
with something more interactive and alive than a report. That's the
same difference as between a paper and a conference presentation or
live demo.

**Comment by nthiery** [comment] 2017-04-18 19:01
>    Clement has asked for 2-3 slides per deliverable. I assume that's
>    reasonable.

Yup. And then he might fuse/refactor/... the material. At the end the
WP presentations are just 1/2h long, questions and transitions
included.

**Comment by wbhart** [comment] 2017-04-18 19:02
Ah, I see. So the work package presentations will tie the individual
deliverables together in context, and the entire presentation will tie the
work packages together. I'll try to bear that in mind when writing slides.

**Comment by bpilorget** [comment] 2017-04-18 19:13
Exactly Bill +1

**Comment by ClementPernet** [comment] 2017-04-18 20:21
I confirm what has been said above: I asked each Task leader of WP5 to send me 2-3 slides on their 
contributions.
I will then merge and rearrange them into the WP5 presentation.

I let task leader free to choose which ever slide format they preferred. I'll merge everything into 
a single format, eigher beamer or the markdown template. I'm not decided about that now.
Best
Clément

**Comment by VivianePons** [comment] 2017-04-18 20:33
Please, if anyone is making a beamer presentation and replicating the
markdown first page (with the logo and all), could you share your template
so that we don't have to do this multiple times?


2017-04-18 22:21 GMT+02:00 Clément Pernet <notifications@github.com>:

**Comment by kohlhase** [comment] 2017-04-19 06:14
I am starting the presentations, but I cannot include images. The docu says `![alt](url)`, but that does not work for me. Can anyone help?

**Comment by VivianePons** [comment] 2017-04-19 07:24
I can help: first check if you can access the image directly and that the
link on slide is correct. If the problem is still here, please open another
issue where we can discuss / fix it without overflowing this thread.

Best,

Viviane

2017-04-19 8:14 GMT+02:00 Michael Kohlhase <notifications@github.com>:

**Comment by fangohr** [comment] 2017-04-19 15:41
Regarding demonstrators: we need a few more I reckon'. I have added Jupyter- OOMMF to the list at the top of this issue. 

@bpilorget - do we know what kind of room layout and facilities we expect? Have we got tables where we can put a laptop on top for the demonstrator? Can we have a poster next to it to attract some attention to the laptop? (This setup would work well I think, and is also what @wdecker reported to have used I believe.

**Comment by fangohr** [comment] 2017-04-19 15:49
There is a bit of a discussion on the talks in the morning of Wednesday 26 April taking place on Slack between those giving the talks (Nicolas, Viviane, Mike, Hans), to coordinate content, order, timings, etc. If anybody else wants to engage, join us at https://opendreamkit.slack.com/messages/C51ASH3V3  (I can invite people to Slack if required).

<pre>
9:00 Welcome
  Overview of the day by Project Officer
  Go around the table
  Brief overview of the project @nthiery
9:30 Some context and case studies
  1: Is your research software correct? @mikecroucher?
  2: A case study of computational science in Jupyter notebooks: JOOMMF @fangohr
  3: SageMathCloud for teaching and research @vivianepons
10:45 Coffee break
</pre>

**Comment by kohlhase** [comment] 2017-04-19 16:50
I guess WP6 has not talked about the demos yet. Mostly because we are still working on this. But here is what we are planning 
- In-Document computation demo (for D4.9)
- The MitM, GAP, Sage and LFMDB Theory graph (with first interview alignments) for D6.2/3
- MathWebSearch on OEIS and arXiv (for D6.1) 
- the WP6 interoperability example (looking up transitive groups in LMFDB, letting MMT send them between SAGE? and GAP). 
All of these should be showable on  @Jazzpirate's  laptop (but only if we access to our various servers in Bremen).

**Comment by kohlhase** [comment] 2017-04-19 16:53
QUESTIONS: (I only realize them now that I am really thinking about demos)
- [ ] Will we have Internet on Wednesday?
- [ ] Will we be able to print posters in Brussels (if we can make PDFs?)
The first is extremely important for our demos, and the second one would make it much more likely that we will have posters.

**Comment by bpilorget** [comment] 2017-04-19 16:57
Of course there will be internet all three days. It will be in the same building.
There will be no printer for posters per se, no. Were you planning do build the posters next week?

**Comment by kohlhase** [comment] 2017-04-19 17:00
> Of course there will be internet all three days. It will be in the same building.

very good.

**Comment by kohlhase** [comment] 2017-04-19 17:01
> There will be no printer for posters per se, no. Were you planning do build the posters next week?

I was contemplating my options. The demos will probably be last-minute, and if the posters are going to be useful, they need to be last-minute as well. 
And if I have to decide between a poster and a demo, the latter has priority for me. 
So being able to print posters on tuesday would be quite helpful.

**Comment by nthiery** [comment] 2017-04-19 17:12
>    So being able to print posters on tuesday would be quite helpful.

I imagine we can find a print shop somewhere not too far in Brussels.
It would be safe to double check though.

**Comment by pdehaye** [comment] 2017-04-19 17:16
There are several near my parents, where I am staying. Will check tonight/tomorrow what options they have. 
Paul

**Comment by bpilorget** [comment] 2017-04-19 17:16
But for posters? It is quite specific and can require some time...

**Comment by pdehaye** [comment] 2017-04-20 08:12
So I just called. They can do posters, up to A0. They open at 8:45am and
close at 6pm, they need 24 hours to print. So it could theoretically work
with me picking it up on Wednesday morning. Only catch is that it is super
expensive: 95 EUR for A0 (picture quality printer).

**Comment by kohlhase** [comment] 2017-04-20 08:41
Thanks for this. I will have a look at what I can do here and keep this in mind if If this does not work out.

**Comment by kohlhase** [comment] 2017-04-20 08:43
I have given up on the metadata slides for the moment and I will prepare my talk in beamer (more efficient, and maybe I can transfer the talk to md style in Brussels). 
For that I am working on a beamer ODK theme. Can someone tell me where I can find the new watermark picture? So that we can use it in the theme?

**Comment by VivianePons** [comment] 2017-04-20 08:46
It's here:

https://github.com/OpenDreamKit/OpenDreamKit/blob/master/Communication/logos/banner.svg

the picture does not have the watermark effect in itslef, it is done by the
style sheet.

2017-04-20 10:43 GMT+02:00 Michael Kohlhase <notifications@github.com>:

**Comment by kohlhase** [comment] 2017-04-20 08:46
thanks, beamer is good at watermarking, so that is not a problem.

**Comment by VivianePons** [comment] 2017-04-20 08:48
Remark: there is no need to convert your slides to markdown if you do them
in beamer (especially if the front page has a similar look).

I did the markdown ones so that we could use the metadata and to have a
reference / example for all of our slides.

2017-04-20 10:45 GMT+02:00 Viviane Pons <vivianepons@gmail.com>:

**Comment by kohlhase** [comment] 2017-04-20 08:52
OK, then I will try to make a good ODK theme for beamer and put it somewhere for everyone to use (and improve).

**Comment by kohlhase** [comment] 2017-04-20 10:20
I just committed ```OpenDreamKit/lib/sty/beamerthemeODK.sty```
So if you add ```OpenDreamKit/lib/sty//``` to ```TEXINPUTS```, then you can just use ```\usetheme{ODK}``` in your beamer slides.

**Comment by VivianePons** [comment] 2017-04-20 12:23
@kohlhase Thank you! That will be very useful for everyone who wish to use beamer

**Comment by VivianePons** [comment] 2017-04-20 12:28
I just pushed a first draft of my WP2 presentation

http://opendreamkit.org/meetings/2017-04-26-ProjectReviewPresentations/WP2/

For those using markdown, it will maybe give you a more concrete example that the current models.

@alex-konovalov Could you please fill out 1 our 2 slides on the *Computational Mathematics with Jupyter* event? (who was there, what we talked about, pictures, whatever)

@fangohr Could you describe a bit more what you do with JOOMF and micromagnetic VRE (2-3 slides)? I left a section on the slides for you to fill

**Comment by kohlhase** [comment] 2017-04-20 13:50
I found out about printing posters at FAU, ... and maybe I can make some before tomorrow, ... 
Please tell me: what size of posters do we want? 
I have a demo for WP4 and two for WP6, should I make two posters? Or combine them (there is only one laptop to demo in any case). 
Please advise soon, then I can probably make a poster here.

**Comment by bpilorget** [comment] 2017-04-20 14:38
I guess what Nicolas had in mind was an A0 poster. As for how many to print... That would be good to have one for WP4 and one for WP6 if they both make sense.

Please don't forget to include acknowledgement http://opendreamkit.org/acknowledge/

**Comment by nthiery** [comment] 2017-04-20 14:40
>    I found out about printing posters at FAU, ... and maybe I can make
>    some before tomorrow, ...
>    Please tell me: what size of posters do we want?
>    I have a demo for WP4 and two for WP6, should I make two posters? Or
>    combine them (there is only one laptop to demo in any case).
>    Please advise soon, then I can probably make a poster here.

It's hard to tell without actually seeing/manipulating. Just go for
whatever feels right to you! We should have enough space in the room
to adapt to anything.

**Comment by jdemeyer** [comment] 2017-04-20 15:04
@mikecroucher: I seem to recall from Edinburgh that you had some demonstrations for interacts. Could some of those be used for a demonstrator?

Or do other people have cool interacts?

There is some ODK relevance because part of [D4.5](https://github.com/OpenDreamKit/OpenDreamKit/issues/94) is porting SgaeNB interacts to Jupyter.

**Comment by nthiery** [comment] 2017-04-20 15:45
>    [1]@mikecroucher: I seem to recall from Edinburgh that you had some
>    demonstrations for interacts. Could some of those be used for a
>    demonstrator?
> 
>    Or do other people have cool interacts?
> 
>    There is some ODK relevance because part of [2]D4.5 is porting SgaeNB
>    interacts to Jupyter.

Yes! And also that's one ingredient in our argument in favor of
REPL/notebook based VREs: they also enable researchers to relatively
easily build and deploy widget/form based (aka clic-clic) user
interfaces on top of them.

@VivianePons: could you include one or two interacts in your demo?

**Comment by jdemeyer** [comment] 2017-04-20 18:04
Do you want me to check some shop in Gent for the posters?

**Comment by mikecroucher** [comment] 2017-04-22 11:21
The interacts that we did for Edinburgh are rather basic.

The effort at Edinburgh was focused on getting started and putting something in place for others to contribute to.  Finishing this work is one of our future deliverables but we don't have much to show for this review I'm afraid.

If anyone would like to contribute a notebook, the template is at 

https://github.com/mikecroucher/jupyter-interactions/blob/master/template.ipynb 

Rename the template, use it to write your interaction and submit a PR.
The template needs to be strictly adhered to in order for things to work.

The website https://mikecroucher.github.io/jupyter-interactions/ is automatically built from this repo once the PR is accepted.  Currently only notebooks that produce an image are supported. This means that, for example, this notebook doesn't get added to the website https://github.com/mikecroucher/jupyter-interactions/blob/master/fractions.ipynb

**Comment by minrk** [comment] 2017-04-22 13:57
I'll have demos prepared for nbval and nbdime (D4.6, D4.8).

**Comment by alex-konovalov** [comment] 2017-04-24 14:54
@VivianePons I've added ICMS slide in https://github.com/OpenDreamKit/OpenDreamKit.github.io/commit/a388a99385ea83c4ad9e4a5cdde070cf6a8e7a45

**Closed** 2017-05-19 09:25 UTC
