### ISSUE TITLE
D7.1: The flow of code and patches in open source projects

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#148] opened 2015-09-08 20:22 UTC
- **WP7:** [Social Aspects](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP7)
- **Lead Institution:** University of Oxford
- **Due:** 2017-02-28 (month 18)
- **Nature:** Report
- **Task:** T7.1 (#144): Social input to design
- **Proposal:** [p. 58](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) 
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP7/D7.1/report-final.pdf)**

OpenDreamKit builds on top of a large ecosystem of (mostly) academic open-source systems, many of which are large-scale themselves: for example our chosen test system [SageMath](http://sagemath.org) is the outcome of a decade of work by hundred of contributors; many others are decades old. The social engineering aspects involved in such a large ecosystems are therefore both intricate and central for its long run sustainability. This motivates OpenDreamKit's objective in WP7 of studying the collaborative processes of free open source (mathematical) software development so as to produce guidelines for best practice as well as to develop ideas for extending existing processes to an “ecosystem of systems”.

In this deliverable we survey the methodology, data, and tools needed to assess development models of large-scale academic open-source systems, such as the probable correlation between the size of the atomic contribution vs. the speed of the contribution making it into the code, and collect appropriate statistical data, to be published as a report (and possibly a conference publication). While in the proposal it was assumed that the latter might require non-trivial amount of programming work, even only for our test system, great open-source tools to address precisely these kinds of questions were released last year, and we used one of them instead. 

Accomplishments:

- [x] a large number of publications and online sources was reviewed for applicability
- [x] various analytic tools were tried on a sample of SageMath components
- [x] results were summarised in a report, with conclusions and pointers to further possible developments

**Comment by alex-konovalov** [comment] 2016-06-29 22:01
This is interesting: https://github.com/blog/2195-the-shape-of-open-source. As @arfon explained, there is no tool to produce such visualisation for other repositories: it was a combination of D3 and MySQL queries against GitHub databases. One could try to look at http://grimoirelab.github.io/ and https://cauldron.io/

**Comment by alex-konovalov** [comment] 2016-06-29 22:36
P.S. Hot off the press: https://github.com/blog/2201-making-open-source-data-more-available

**Comment by npch** [comment] 2016-08-11 15:59
It might be interesting to use the tidytext package to do analysis of some of this data extracted into tidy data form - see http://juliasilge.com/blog/Life-Changing-Magic/ http://varianceexplained.org/r/trump-tweets/

**Comment by bpilorget** [comment] 2016-11-21 16:25
@dimpase (WP leader and lead beneficiary)
This deliverable is due for February 2017

**Comment by nthiery** [comment] 2017-02-06 17:50
Dear M18 deliverable leaders,

Just a reminder that reports are due for mid-february, to buy us some time for proofreading, feedback, and final submission before February 28th. See our [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable) for details on the process.

In practice, I'll be offline February 12-19, and the week right after will be pretty busy. Therefore, it would be helpful if a first draft could be available sometime this week, so that I can have a head start reviewing it.

Thanks in advance!

**Comment by bpilorget** [comment] 2017-02-22 09:25
@dimpase How is everything going? A report must be delivered by the 28th February

**Comment by dimpase** [comment] 2017-02-26 17:05
@bpilorget @nthiery I commited the 1st draft, will do a bit of fiddling, like proofreading etc, but that's basically done, as far as I am concerned.

**Comment by nthiery** [comment] 2017-02-26 23:06
Hi @dimpase,

Thanks for this first draft; that's an interesting survey of the litterature.

I proofread the tex file, fixed some minor typos and pushed.

For the abstract (aka github issue description), please edit the first comment on this issue, rather than the markdown file in the repo. To automatically update the latter:

    rm WP7/D7.1/report.pdf WP7/D7.1/github-issue-description.*
    make WP7/D7.1/report.pdf

In terms of the content of the abstract, you may want to take e.g. #98 as an example, and check the notes in the [README](https://github.com/OpenDreamKit/OpenDreamKit/#submitting-a-deliverable).

TODO:
- In the abstract and/or the report itself: clarify what was achieved for this deliverable in addition to reviewing the litterature: which data was or will be collected, which tool was or will be implemented, etc.
- In the conclusion: "ought to be developped": does this just mean that this is required to derive significant conclusions, or that we actually are planning to do it as part of ODK?
- @alex-konovalov: could you please have a look at the report and provide feed back?

Thanks in advance!

**Comment by dimpase** [comment] 2017-02-26 23:43
@nthiery Thanks. I followed your instructions: edited the 1st comment; removed `github-issue-description.*`, then `make` failed, as it complained about inability to find `github-issue-description.md` - and so I put the latter back. Then `make` did run, and created pdf - with an empty abstract.
Do you mean to say that `github-issue-description.tex` is meant to be generated by getting the 1st comment from github (via its API?) ?

**Comment by alex-konovalov** [comment] 2017-02-27 00:33
Thanks. From a quick glance what I can see is:
- need to update issue description in the report
- figure 2 matches my impression
- Figure 3 also matches my "if it's done, it's done" motto: most of PR are closed quickly.
- figure 3 is not easy to read initially; both figures would benefit from some text describing what's there.
- can we have an equivalent of figure 3 for open issues?
- for GAP, you may wish to cite this blog post http://www.codima.ac.uk/2016/03/09/gap-on-github-one-year-on/ somewhere
- desirable to have more pictures, not only about GAP. Can we analyse some other repositories?

**Comment by alex-konovalov** [comment] 2017-02-27 00:50
Time permitting, I'd like a better horizontal resolution and individual months on Fig.3, and also more clearly indicated month markers on the horizontal axis.

**Comment by nthiery** [comment] 2017-02-27 06:43
On Sun, Feb 26, 2017 at 03:43:06PM -0800, Dima Pasechnik wrote:
>    [1]@nthiery Thanks. I followed your instructions: edited the 1st
>    comment; removed github-issue-description.*, then make failed, as it
>    complained about inability to find github-issue-description.md
>    Do you mean to say that github-issue-description.tex is meant to be
>    generated by getting the 1st comment from github (via its API?) ?

Yes.

Ah, I see from the repo that you committed an updated abstract. So I
assume this worked at the end, right?

**Comment by dimpase** [comment] 2017-02-27 07:14
@nthiery it did work, yes---although there is some strange ` {.notoc}\n` string that makes it all way into the resulting pdf. Not sure where it comes from, it is already in markdown.

**Comment by nthiery** [comment] 2017-02-27 08:06
Just to avoid conflicts: I am now about to do some minor edits to the issue description and report, and check the .notoc thingy at this occasion.

**Comment by nthiery** [comment] 2017-02-27 08:51
On Sun, Feb 26, 2017 at 11:14:05PM -0800, Dima Pasechnik wrote:
>    [1]@nthiery it did work, yes---although there is some strange
>    {.notoc}\n string that makes it all way into the resulting pdf. Not
>    sure where it comes from, it is already in markdown.

This is probably just a glitch due to a different version of
pandoc. Just ignore it; I'll do the very final update.

Cheers,
		Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/

**Comment by dimpase** [comment] 2017-02-27 08:52
just for the record: I used
```
$ pandoc -v
pandoc 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9.1, skylighting 0.3
```

**Comment by nthiery** [comment] 2017-02-27 09:00
Ok; thanks for the info. My pandoc is older :-) Anyway; no big deal, to be investigated later.

**Comment by dimpase** [comment] 2017-02-27 09:03
are you done? I'd like to add more graphs...

On Mon, Feb 27, 2017 at 9:00 AM, Nicolas M. Thiéry <notifications@github.com

**Comment by nthiery** [comment] 2017-02-27 09:03
@OpenDreamKit/wp7: feedback on the report for this deliverable is welcome! You can access the current pdf by clicking "Final report" above. Well, it's not quite final, but will be soon :-)
@dimpase: you may want to update report-final.pdf from time to time.

**Comment by nthiery** [comment] 2017-02-27 09:04
Yes, I am done! (see also my private e-mail)

**Comment by dimpase** [comment] 2017-02-27 11:09
I've edited the D7.1 description to indicate software availability, as discussed, and pushed the corr. changes. Now to teaching, till the evening.

**Comment by alex-konovalov** [comment] 2017-02-27 16:40
I can't build the bibliography. Can you?

**Comment by dimpase** [comment] 2017-02-27 16:44
well, yes, how would I have built the pdf otherwise?
What's the error you get?

**Comment by alex-konovalov** [comment] 2017-02-27 16:46
@dimpase I am now doing some minor edits in a branch - will make a PR for you to review

**Comment by alex-konovalov** [comment] 2017-02-27 22:54
I've submitted PR #219 merged by @dimpase. I also think that the section "Openness, licensing, etc" is not necessary. There is no unique point of view here - while @dimpase argues that GPL-style licenses are "better in sense of keeping the community together", many open science advocates will advice to use as permissive license as possible to facilitate maximal reuse and this may point to other licenses. From my point of view, the topic is "The flow of code and patches in open source projects" and it's not required to cover licenses here.

**Comment by dimpase** [comment] 2017-02-28 08:14
Well, flow of code and patches depend on the license type, no doubt.

The only place where more permissive is better is commercialisation. Licenses are akin to locks.
If you do not lock your bicycle it will be more used, and indeed it's more convenient not to bother with the locks, the problem is that very soon you might not see it again :-). As we are interested in building an open-source VRE, a long-term project, better locks might come handy...

**Comment by dimpase** [comment] 2017-02-28 18:26
as far as I am concerned it is ready for submission. But feel free to modify...

**Comment by nthiery** [comment] 2017-02-28 20:03
Cool. @alex-konovalov or anyone from @OpenDreamKit/wp7: let me know if you still want to do some work on this deliverable.
By default, I am now planning to spend about one hour on D1.4, and submit this one after.
Cheers,

**Comment by alex-konovalov** [comment] 2017-02-28 20:29
@nthiery I have several typos fixed - will push soon. But the question about section 6 still remains open...

**Comment by nthiery** [comment] 2017-02-28 20:39
I agree with @dimpase that there is something to be said about licences; they certainly do influence the flow of code and patches. So often it's licensing issues that have prevented the flow of code from otherwise usefull software. We could mention a couple striking examples which hurt us badly, like gap3, Nauty, or graphviz which we could not include as standard packages in Sage.
That being said, I agree with @alex-konovalov  that I'd rather avoid getting into opinions and religious debates about the pros and cons of specific licences.
Anyone up for a quick rewrite of this section in the next hour or so?
Otherwise, I'll just strip out the section and submit.

**Comment by dimpase** [comment] 2017-02-28 20:50
I can tone this down, but I don't think removing it completely makes sense. IMHO in UK in particular it has become so customary to ignore open source as something that does not make £££ (impactwise, too EPSRC until recently absolutely did not encourage any open-source projects whatsoever), and so the opinion in universities was always tilted toward easy commercialisation. But we are not aiming at selling ODK to the highest bidder, do we?

Further I really do not see a harm in mentioning our point of view in the report.

**Comment by alex-konovalov** [comment] 2017-02-28 21:10
@dimpase it's basically about the 2nd paragraph.

**Comment by nthiery** [comment] 2017-02-28 21:26
I agree about mentionning our point of view about open source licenses. But for GPL vs BSD this is not even something there is a consensus about in ODK. E.g. Jupyter uses revised BSD.

**Comment by nthiery** [comment] 2017-02-28 21:28
I can just remove the paragraph about GPL vs BSD. But then section 6 becomes rather tiny, unless it gets fleshed up a bit, e.g. with some Nauty/... story.
Thus, let me ask again: is there someone ready to take the time to implement that now?
We need to submit, and I need to go to bed not too late :-)

**Comment by alex-konovalov** [comment] 2017-02-28 21:49
Interesting link: https://choosealicense.com/appendix/

**Comment by nthiery** [comment] 2017-02-28 22:21
For the record: we resolved the Section 6 status by chatting on gitter.

**Comment by dimpase** [comment] 2017-02-28 22:22
I propose to include in Sage a module written in this [language](https://en.wikipedia.org/wiki/Brainfuck) and licenced under https://choosealicense.com/licenses/wtfpl/

**Comment by nthiery** [comment] 2017-02-28 22:23
Submitted!
Thanks @dimpase for your work on this deliverable and report, both being borderline w.r.t. our usual comfort zone :-)
Thanks @alex-konovalov for the reviewing help!

**Closed by nthiery** 2017-02-28 22:23 UTC
Labels: deliverable, UO, WP7
