### ISSUE TITLE
Join EGI/EUDAT  proposal for EINFRA-12-2017(A) Call?

### ISSUE THREAD

**Issue by bpilorget** [OpenDreamKit/OpenDreamKit#205] opened 2016-10-26 08:27 UTC
# Call: [EINFRA-12-2017](https://ec.europa.eu/research/participants/portal/desktop/en/opportunities/h2020/topics/einfra-12-2017.html)
- Topic identifier:     EINFRA-12-2017
- Publication date:     14 October 2015
- Types of action:  RIA Research and Innovation action
- DeadlineModel:    single-stage
- Planned opening date:  08 December 2016  
- Deadline:     29 March 2017 17:00:00

[Repository for ODK's participation](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3/EINFRA-12-2017)
[Call for expression of interest to the EGI-EUDAT proposal](https://eudat.eu/news/egi-eudat-and-indigo-datacloud-join-forces)

**Comment by bpilorget** [comment] 2016-10-26 08:32
@OpenDreamKit/steering 
You can express your interest here.

I am available to help you prepare to join the proposal if the choice is taken to join EGI/EUDAT as it is a task to disseminate and outreach ODK.
However I must warn you that I would not implement this new Grant as UPSud will of course not be the lead coordinator and as I would not have time at all to deal with this. But I guess such a big project would have all the administration support for the implementation so that is fine.

**Comment by bpilorget** [comment] 2016-12-07 16:43
An "`[e-infrastructure proposer's day](https://ec.europa.eu/digital-single-market/en/news/einfrastructure-proposers-day-2017)`" for this call well be organised in Amsterdam on the 19/01/2017
It is the same day than the project meeting in Edinburgh. But maybe we can contact the EGI meeting beforehand.

@OpenDreamKit/steering

**Comment by bpilorget** [comment] 2016-12-13 15:25
Use case available to work on the call: https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP3/2016-09-27-DesignYourInfrastructureWorkshop-UseCase.md

**Comment by nthiery** [comment] 2017-01-24 21:34
EGI/Eudat made an explicit call to join. Deadline for applying is this Friday. If you haven't received Benoît's email on the topic, let him know.

**Comment by jgmbenoit** [comment] 2017-01-25 04:24
Am I the involved Benoit ? If so, please give me a relevant link about it.

**Comment by nthiery** [comment] 2017-01-25 07:26
I meant @bpilorget :-) That being said, in case you would be interestested in the deployement of services like mybinder or JupyterHub on the EU cloud, you are of course welcome to join.

**Comment by takluyver** [comment] 2017-01-25 15:08
I'm having a go at the proposal, at Hans' request, but I haven't done anything like this before, so I'm not sure if what I'm writing is suitable.

**Comment by minrk** [comment] 2017-01-25 16:14
Thanks, Thomas. Let me know if you'd like a hand with anything in particular.

**Comment by takluyver** [comment] 2017-01-25 16:52
Thanks. I've been focussing on the 'relevance' section; I've just pushed comments for a couple of points that I don't know what they mean. If they're clearer to you, that would be valuable.

Looking at the template, I think we also need some more detail on the services we're talking about and how we propose to integrate them with the infrastructure. I don't know if that means we're meant to know the details of the infrastructure in question as we write them - I don't, so I can only talk about integration in very generic terms.

**Comment by takluyver** [comment] 2017-01-25 16:57
I'm also having trouble fitting the pieces we're proposing into the 'service' description the template uses - things like an access policy and a business model assume that it's something you already run as a massive centralised deployment, whereas we're proposing new deployments of existing software.

**Comment by nthiery** [comment] 2017-01-25 17:03
On Wed, Jan 25, 2017 at 08:52:28AM -0800, Thomas Kluyver wrote:
>    Thanks. I've been focussing on the 'relevance' section; I've just
>    pushed comments for a couple of points that I don't know what they
>    mean. If they're clearer to you, that would be valuable.

@mikecroucher: you have a good experience highlighting what's important for software for research (version control, reproducibility, ...); could you have a look?

>    Looking at the template, I think we also need some more detail on the
>    services we're talking about and how we propose to integrate them with
>    the infrastructure. I don't know if that means we're meant to know the
>    details of the infrastructure in question as we write them - I don't,
>    so I can only talk about integration in very generic terms.

I would say that this is fine; they plausibly run a variety of infrastructure anyway. In fact, we can argue that discussing the fine details of integration is precisely one of the task to do with them and the point of being in a joint project.

**Comment by dimpase** [comment] 2017-01-25 17:03
@takluyver - our "massive centralised deployment" can be SageMathCloud. Indeed, the call wants something that was already demonstrated to be feasible (and jupyterhub, naturally).

**Comment by nthiery** [comment] 2017-01-25 17:04
And also the current mybinder deployement which has proven the value of the model; being in fact too successful for the underlying resources!

**Comment by nthiery** [comment] 2017-01-25 17:07
For the lock-in: you can further advertise that the Jupyter architecture is highly modular. In particular that the users can switch computing backend while remaining in the same environment.

**Comment by nthiery** [comment] 2017-01-25 17:11
> 2. All European researchers and educators are in equal footing to access essential resources
I guess unequal footing would be when people in rich institution/countries have access to plenty of resources (because the institution can pay for hardware, licences, ...) and not others.

**Comment by nthiery** [comment] 2017-01-25 17:15
Thanks @takluyver, this is taking a good start!

**Comment by bpilorget** [comment] 2017-01-26 16:02
Hi @takluyver  it is important to respect the template that was fiven for the call. The information we are providing must (perfectly) fit in their template , and not the other way around :)

**Comment by bpilorget** [comment] 2017-01-26 16:05
At this stage all information I have legally speaking is that OpenDreamKit is not an adequate legal person to legally create a Jupyter hub for the Proposal we are answering to.
However we can still use the ODK brand, propose a Work Package (or tasks) around Jupyter while clearly stating your legal institutions would have to get on board.

I'll push something in the Proposal myself to explain this.

**Comment by bpilorget** [comment] 2017-01-26 16:40
@takluyver 
For the 4th challenge of EINFRA-12 to answer (Train people in academic and research): On the official call it is written: "adoption of standards-based common interfaces, open source components enabling access and processing of underlying data collected/stored in different platforms and formats. Empowering users to customise application and services tailoring them to specific requirements, which will differ across disciplines, applications etc".

So it does mean we train users how to use the service.

**Comment by bpilorget** [comment] 2017-01-26 16:50
I'm going to make changes to the proposal now so that all you have to do is fill in the paragraphs

**Comment by takluyver** [comment] 2017-01-26 16:52
Thanks @bpilorget !

**Comment by bpilorget** [comment] 2017-01-26 17:41
Ok I'm done updating the document for now @takluyver

**Comment by bpilorget** [comment] 2017-01-26 17:51
@nthiery @takluyver @minrk @dimpase @mikecroucher @fangohr 
After some admin research it seems that OpenDreamKit is not a right legal body in order to apply to become a partner of the furture EINFRA12 consortium project. Even through UPSUD.

So I am proposing in the Expression of interest that is being filled now we still use the "umbrella" OpenDreamKit while stating that the legal bodies per se will be other institutions (yours) and that you are willing to work together within the future consortium inside a WorkPackage or Tasks.

For that we need to know the legal entities that are currently interested to join. I have so far: Southampton, Simula, Oxford and Sheffield. Should we count others?

Also we need to tell in the expression of interest how much person-months we need for the three services we wish to develop (mybinder, tmpnb and jupyterhub). That must be done for tomorrow. Sorry for the rush...

**Comment by mikecroucher** [comment] 2017-01-26 18:21
In addition to the three services mentioned above, would there be scope to use this call expand on the work Sheffield has done on integrating Jupyter with Sun Grid Engine schedulers? https://github.com/OpenDreamKit/OpenDreamKit/issues/116 

I'm thinking more schedulers, integration with the new Tier-2 HPC infrastructure that the UK is developing (strategy - https://www.epsrc.ac.uk/files/research/tier2hpcstrategy/ funded centres here: http://gow.epsrc.ac.uk/NGBOViewPanelROL.aspx?PanelId=1-414KW8&RankingListId=1-414KWJ) along with HPC integration of frameworks such as Southampton's Micromagnetics/Jupyter demonstrator. 

Someone else mentioned including dask and I've sometimes wondered if joblib could be used here too?

Is such work suitable for this call or have I missed the point

**Comment by minrk** [comment] 2017-01-26 19:09
@mikecroucher that seems appropriate to me. We just need to work out how much time we have to spend on each. Dask & Joblib would be effectively the same work - dask and IPython Parallel function as backends for joblib, so if you can get dask or IPython Parallel on the cluster, you can run joblib on top.

**Comment by dimpase** [comment] 2017-01-26 19:14
Please feel free to allocate Oxford  few pm's, or scratch it out all together; it looks very jupyter-centric to me, and I don't see how I can contribute meaningfully, unless it is backend and testing only.

**Comment by dimpase** [comment] 2017-01-26 19:17
something about alpha-testing for teaching purposes; we teach some large classes using SMC, but would gladly try out something more flexible in deployment sense.

**Comment by jdemeyer** [comment] 2017-01-26 20:17
> @mikecroucher that seems appropriate to me. We just need to work out how much time we have to spend on each. Dask & Joblib would be effectively the same work - dask and IPython Parallel function as backends for joblib, so if you can get dask or IPython Parallel on the cluster, you can run joblib on top.

This is a bit off-topic, but I have been looking for a while for a robust multiprocessing library in Python. Anybody has a suggestion?

I am looking for something simple (a pool of workers on a single machine) but it needs to be robust under failure conditions. I could actually write it myself (I did that for the Sage parallel doctester) but I don't want to reinvent the wheel. The Sage doctesting frameworks handles interrupts, hung processes, crashes, exceptions and I haven't found a Python library which does the same (I looked at Python's `multiprocessing` and joblib).

**Comment by mikecroucher** [comment] 2017-01-27 08:52
I've been adding minor additions to the document but think I need to discuss stuff with co-authors in something close to realtime. @minrk, @takluyver, @nthiery -- do any of you use Slack or similar?

**Comment by fangohr** [comment] 2017-01-27 09:22
Hi Mike, I'll catch up with Thomas in a moment, and will then have a look at where we are and try to see what is missing. I am happy on Slack for example opendreamkit.slack.com - if anybody wants to join, please shout and I'll send an invite. I need another 2 hours or so to do the catch up, but then it'll be high time to get this proposal idea completed :)

**Comment by mikecroucher** [comment] 2017-01-27 09:27
Sounds great. I am more than happy to be involved but I don't have the resources or experience to lead this I'm afraid.

**Comment by minrk** [comment] 2017-01-27 09:33
@fangohr I'd like an invite. I'll be around today, but also working on presentation things that I need to finish by this evening.

**Comment by bpilorget** [comment] 2017-01-27 09:55
I will be available all afternoon if needed so you can send me an invite too

**Comment by nthiery** [comment] 2017-01-27 10:27
Hi Mike!

On Thu, Jan 26, 2017 at 10:21:39AM -0800, Mike Croucher wrote:
>    In addition to the three services mentioned above, would there be scope
>    to use this call expand on the work Sheffield has done on integrating
>    Jupyter with Sun Grid Engine schedulers? [1]#116

What we can request is funding for work on integration of Jupyter in
the EGI/EUDAT infrastructures. If some of those insfrastructures
include use Sun Grid Engine schedulers, or if there is generic stuff
that would be both useful for SGE and other infrastructures, then I
believe the answer is yes.

In any case, pointing out that we do have experience integrating
Jupyter on grid infrastructures is very worthwhile.

**Comment by nthiery** [comment] 2017-01-27 10:33
On Fri, Jan 27, 2017 at 01:22:51AM -0800, Hans Fangohr wrote:
>    Hi Mike, I'll catch up with Thomas in a moment, and will then have a
>    look at where we are and try to see what is missing. I am happy on
>    Slack for example opendreamkit.slack.com - if anybody wants to join,
>    please shout and I'll send an invite. I need another 2 hours or so to
>    do the catch up, but then it'll be high time to get this proposal idea
>    completed :)

I should be able to join on and off today. Please send an invite!

**Comment by takluyver** [comment] 2017-01-27 23:00
Thanks everyone for helping to get this together in time! We submitted the expression of interest document with 20 minutes to spare. I'm going to close this issue now; if they invite us to submit more info we can either work in a new issue or reopen this.

**Closed by takluyver** 2017-01-27 23:00 UTC
Labels: WP1, WP2

**Comment by dimpase** [comment] 2017-01-28 09:51
where can one find the submitted doc?

**Comment by takluyver** [comment] 2017-01-28 09:58
It should be with the working materials in github. The folder is under WP3.

**Comment by dimpase** [comment] 2017-01-28 10:01
OK, it's 918d0d32b64944f544782c087d3d09ce8b076441 --- thanks!

**Comment by fangohr** [comment] 2017-02-11 09:57
Update: this expression of interest was not successful:

<pre>
Thank you for your application to the e-Infra-12 Thematic Services call and for the time you have
invested in preparing your contribution. Over 60 high-quality applications were submitted in this call.

I regret to inform you that your application has been evaluated with great interest, but was not
shortlisted by the evaluators, reason being that it was considered to be more relevant to the
"specialized services" programme.

A dedicated call will be opened later on in February. If you are interested in applying to it,
please let us know, we will be happy to notify you.
</pre>

We have expressed our interest.

**Comment by dimpase** [comment] 2017-02-11 10:47
let's hope it's just a temporary setback.

**Comment by nthiery** [comment] 2017-02-14 11:21
On Sat, Feb 11, 2017 at 01:57:46AM -0800, Hans Fangohr wrote:
>    Update: this expression of interest was not successful:

Too bad. At least we got a quick answer and feedback showing tentative
interest. So it was worth the shot.

It would have been helpful if they had advertised in advance all the
calls they were planning for, so that we could have aimed right away
at the most appropriate one.

Anyway, we should apply for the "specialized services call", right?
Hopefully the application file should be similar, so that should not
be too much work.

Hans, do you mind requesting the notification?

Cheers,
                                                Nicolas

**Comment by fangohr** [comment] 2017-02-14 11:23
Thomas has already requested the notification.

**Comment by nthiery** [comment] 2017-04-15 22:09
Any news on the front of EGI's specialized services call?

**Comment by fangohr** [comment] 2017-04-15 22:45
I haven't heard anything. @takluyver?

**Comment by takluyver** [comment] 2017-04-18 15:08
Nope, haven't heard anything.

**Comment by nthiery** [comment] 2017-04-18 18:02
>    Nope, haven't heard anything.

And now, from the answer from Gregory, we know that there will be no
specialized service call ... Too bad.

**Comment by bpilorget** [comment] 2017-04-18 18:07
What's the answer?

**Comment by nthiery** [comment] 2017-04-18 18:37
Forwarding the e-mail to you.
